server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://47.97.110.1:3306/evaluation_model?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a8223033
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      max-wait: 60000
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      validation-query: SELECT 1 FROM DUAL

mybatis-plus:
  typeAliasesPackage: com.ln.evalmodel.model
  mapper-locations: classpath:com/ln/evalmodel/dao/mapping/*.xml   #注意：一定要对应mapper映射xml文件的所在路径
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com.lucifer.springboot.cache.mapper: debug